const restaurantsData = [
  {
    id: 1,
    name: "Churrascaria Fogo de Chão",
    rating: 4.7,
    reviewsCount: 3,
    address: "Avenida Paulista, 1000 - São Paulo, SP",
    bannerImage: "/assets/img/banner/banner.jpg",
    image: "/assets/img/foods/Picanha na Brasa.jpg",
    description: "Tradicional churrascaria com rodízio de carnes nobres e buffet variado. Ambiente aconchegante para toda a família.",
    category: "Churrascaria",
    menu: [
      { id: 1, name: "Picanha na Brasa", price: 49.90, image: "/assets/img/foods/Picanha na Brasa.jpg", category: "Carnes" },
      { id: 2, name: "Costela Assada", price: 45.90, image: "/assets/img/foods/Costela Assada.jpg", category: "Carnes" },
      { id: 3, name: "Linguiça Artesanal", price: 15.90, image: "/assets/img/foods/Linguiça Artesanal.jpg", category: "Acompanhamentos" },
      { id: 4, name: "Salada de Batata", price: 10.90, image: "/assets/img/foods/Salada de Batata.jpg", category: "Saladas" },
      { id: 5, name: "Vinagrete", price: 8.90, image: "/assets/img/foods/Vinagrete.jpg", category: "Acompanhamentos" },
    ],
    reviews: [
      { text: "Melhor churrasco de São Paulo!", rating: 5, date: "01-05-2024" },
      { text: "Ótimo atendimento e carnes de qualidade.", rating: 4, date: "15-04-2024" },
      { text: "Ambiente agradável e comida deliciosa.", rating: 5, date: "10-04-2024" },
    ],
  },
  {
    id: 2,
    name: "Taco Bell",
    rating: 4.3,
    reviewsCount: 10,
    address: "Rua México, 300 - Centro, RJ",
    bannerImage: "/assets/img/banner/banner2.jpg",
    image: "/assets/img/foods/Taco Carne Moída.jpg",
    description: "Fast-food mexicano com opções variadas de tacos, burritos e nachos. Ideal para uma refeição rápida e saborosa.",
    category: "Mexicano",
    menu: [
      { id: 6, name: "Taco Carne Moída", price: 12.90, image: "/assets/img/foods/Taco Carne Moída.jpg", category: "Tacos" },
      { id: 7, name: "Burrito Supreme", price: 15.90, image: "/assets/img/foods/Burrito Supreme.jpeg", category: "Burritos" },
      { id: 8, name: "Nachos com Guacamole", price: 10.90, image: "/assets/img/foods/Nachos com Guacamole.jpg", category: "Entradas" },
    ],
    reviews: [
      { text: "Ótimo custo-benefício!", rating: 5, date: "20-03-2024" },
      { text: "Os tacos são bem r`echeados e saborosos.", rating: 4, date: "10-03-2024" },
    ],
  },
  {
    id: 3,
    name: "Burger King",
    rating: 4.1,
    reviewsCount: 15,
    address: "Av. Brasil, 150 - Belo Horizonte, MG",
    bannerImage: "/assets/img/banner/banner.jpg",
    image: "/assets/img/foods/Whopper.png",
    description: "Famosa rede de fast-food, conhecida pelos hambúrgueres saborosos e variados.",
    category: "Hamburgueria",
    menu: [
      { id: 9, name: "Whopper", price: 19.90, image: "/assets/img/foods/Whopper.png", category: "Sanduíches" },
      { id: 10, name: "Chicken Fries", price: 12.90, image: "/assets/img/foods/Chicken Fries.jpg", category: "Aperitivos" },
      { id: 11, name: "Cheddar Duplo", price: 15.90, image: "/assets/img/foods/Cheddar Duplo.jpg", category: "Sanduíches" },
    ],
    reviews: [
      { text: "O Whopper é incrível!", rating: 5, date: "05-04-2024" },
      { text: "Boa opção de fast-food.", rating: 4, date: "03-04-2024" },
    ],
  },
  {
    id: 4,
    name: "Pizza Hut",
    rating: 4.5,
    reviewsCount: 20,
    address: "Rua das Flores, 50 - Curitiba, PR",
    bannerImage: "/assets/img/banner/banner2.jpg",
    image: "/assets/img/foods/Pizza de Calabresa.jpg",
    description: "Pizza de qualidade com diversos sabores e opções de massa. Perfeito para um jantar em família.",
    category: "Pizzaria",
    menu: [
      { id: 12, name: "Pizza de Calabresa", price: 35.90, image: "/assets/img/foods/Pizza de Calabresa.jpg", category: "Pizzas" },
      { id: 13, name: "Pizza Quatro Queijos", price: 37.90, image: "/assets/img/foods/Pizza Quatro Queijos.jpg", category: "Pizzas" },
      { id: 14, name: "Pizza Vegetariana", price: 32.90, image: "/assets/img/foods/Pizza Vegetariana.jpg", category: "Pizzas" },
    ],
    reviews: [
      { text: "Pizza muito gostosa, entrega rápida.", rating: 5, date: "29-03-2024" },
      { text: "Boa variedade de sabores.", rating: 4, date: "27-03-2024" },
    ],
  },
  {
    id: 5,
    name: "Churrascaria Gaúcha",
    rating: 4.6,
    reviewsCount: 8,
    address: "Av. Rio Grande, 250 - Porto Alegre, RS",
    bannerImage: "/assets/img/banner/banner.jpg",
    image: "/assets/img/foods/Costela Assada.jpg",
    description: "Churrascaria com rodízio completo de carnes nobres e buffet variado.",
    category: "Churrascaria",
    menu: [
      { id: 15, name: "Picanha na Brasa", price: 49.90, image: "/assets/img/foods/Picanha na Brasa.jpg", category: "Carnes" },
      { id: 16, name: "Costela Assada", price: 45.90, image: "/assets/img/foods/Costela Assada.jpg", category: "Carnes" },
      { id: 17, name: "Linguiça Artesanal", price: 15.90, image: "/assets/img/foods/Linguiça Artesanal.jpg", category: "Acompanhamentos" },
    ],
    reviews: [
      { text: "Melhor churrasco de Porto Alegre!", rating: 5, date: "10-03-2024" },
      { text: "Vale muito a pena o rodízio.", rating: 4, date: "08-03-2024" },
    ],
  },
  {
    id: 6,
    name: "Salad House",
    rating: 4.4,
    reviewsCount: 5,
    address: "Rua da Saúde, 75 - Campinas, SP",
    bannerImage: "/assets/img/banner/banner2.jpg",
    image: "/assets/img/foods/Salada Caesar.jpg",
    description: "Saladas frescas e deliciosas com ingredientes de alta qualidade e opções vegetarianas.",
    category: "Saladas",
    menu: [
      { id: 18, name: "Salada Caesar", price: 18.90, image: "/assets/img/foods/Salada Caesar.jpg", category: "Saladas" },
      { id: 19, name: "Salada Grega", price: 20.90, image: "/assets/img/foods/Salada Grega.jpg", category: "Saladas" },
      { id: 20, name: "Salada de Frutas", price: 12.90, image: "/assets/img/foods/Salada de Frutas.jpg", category: "Sobremesas" },
    ],
    reviews: [
      { text: "Excelente opção saudável.", rating: 5, date: "15-03-2024" },
      { text: "Saladas bem frescas e saborosas.", rating: 4, date: "14-03-2024" },
    ],
  },
  {
    id: 7,
    name: "Lanchonete do Zé",
    rating: 4.2,
    reviewsCount: 12,
    address: "Av. Liberdade, 200 - Liberdade, SP",
    bannerImage: "/assets/img/banner/banner.jpg",
    image: "/assets/img/foods/Coxinha.jpg",
    description: "Lanchonete tradicional servindo sanduíches, pastéis e sucos naturais. Ótima opção para uma refeição rápida e saborosa.",
    category: "Lanchonete",
    menu: [
      { id: 21, name: "X-Tudo", price: 18.90, image: "/assets/img/foods/X-Tudo.jpg", category: "Sanduíches" },
      { id: 22, name: "Pastel de Carne", price: 8.90, image: "/assets/img/foods/Pastel de Carne.jpg", category: "Aperitivos" },
      { id: 23, name: "Suco de Laranja", price: 6.90, image: "/assets/img/foods/Suco de Laranja.jpg", category: "Bebidas" },
      { id: 24, name: "Coxinha", price: 5.50, image: "/assets/img/foods/Coxinha.jpg", category: "Aperitivos" },
      { id: 25, name: "Refrigerante", price: 4.50, image: "/assets/img/foods/Refrigerante.jpg", category: "Bebidas" },
    ],
    reviews: [
      { text: "Melhor X-Tudo da cidade!", rating: 5, date: "20-05-2024" },
      { text: "Bom custo-benefício e lanches saborosos.", rating: 4, date: "18-03-2024" },
    ],
  },
  {
    id: 8,
    name: "Subway",
    rating: 4.0,
    reviewsCount: 18,
    address: "Rua das Flores, 12 - São Paulo, SP",
    bannerImage: "/assets/img/banner/banner2.jpg",
    image: "/assets/img/foods/Frango Teriyaki.jpeg",
    description: "Rede de fast-food especializada em sanduíches personalizados e saladas.",
    category: "Lanchonete",
    menu: [
      { id: 24, name: "Italiano B.M.T.", price: 18.90, image: "/assets/img/foods/Italiano B.M.T..jpg", category: "Sanduíches" },
      { id: 25, name: "Frango Teriyaki", price: 19.90, image: "/assets/img/foods/Frango Teriyaki.jpeg", category: "Sanduíches" },
      { id: 26, name: "Cookies", price: 4.90, image: "/assets/img/foods/Cookies.jpg", category: "Sobremesas" },
    ],
    reviews: [
      { text: "Sanduíches sempre frescos!", rating: 5, date: "12-04-2024" },
      { text: "Boa variedade e saudável.", rating: 4, date: "10-04-2024" },
    ],
  },
];

export default restaurantsData;
